// All product images are real photos from the Papermonks studio shoot (Feb 2025)

export const products = [
  // ─── BIG WALLET — €18 ──────────────────────────────────────────────
  {
    id: 1,
    sku: 'BIG-01',
    name: 'Big Wallet — Arta Lupe I',
    shortName: 'Arta Lupe I',
    artist: 'Arta Lupe',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-01-arta-lupe.webp',
    images: ['/images/products/big-01-arta-lupe.webp', '/images/products/hero-lifestyle.webp'],
    description: 'O explozie de culoare și energie. Arta Lupe transformă un sistem de forme mecanice și organice într-o lucrare vibrantă în roșu, portocaliu și turcoaz.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. Imprimat eco, 100% reciclabil. Produs manual în studioul nostru de artă din București.',
    dimensions: 'Portofel mare. Încap bancnote, carduri, bonuri și mai mult. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România. Transport internațional disponibil. Retururi acceptate în 14 zile.',
    stock: 12,
    inStock: true
  },
  {
    id: 2,
    sku: 'BIG-02',
    name: 'Big Wallet — Arta Lupe II',
    shortName: 'Arta Lupe II',
    artist: 'Arta Lupe',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-02-arta-lupe.webp',
    images: ['/images/products/big-02-arta-lupe.webp'],
    description: 'Forme geometrice precise în culori vii — roz, verde, galben, violet. O compoziție care transformă buzunarul tău într-o galerie de artă.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. Imprimat eco, 100% reciclabil.',
    dimensions: 'Portofel mare. Încap bancnote, carduri, bonuri și mai mult. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România. Retururi acceptate în 14 zile.',
    stock: 8,
    inStock: true
  },
  {
    id: 3,
    sku: 'BIG-03',
    name: 'Big Wallet — Coon & Crack I',
    shortName: 'Coon & Crack I',
    artist: 'Coon & Crack',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-03-coon-crack.webp',
    images: ['/images/products/big-03-coon-crack.webp', '/images/products/bundle-hero.webp'],
    description: 'Personaje urbane iconice cu caracter, în culori intense de mov, portocaliu și maro. Arta stradală la cel mai înalt nivel, pliată în portofelul tău.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. Imprimat eco, 100% reciclabil.',
    dimensions: 'Portofel mare. Încap bancnote, carduri, bonuri și mai mult. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România. Retururi acceptate în 14 zile.',
    stock: 15,
    inStock: true
  },
  {
    id: 4,
    sku: 'BIG-04',
    name: 'Big Wallet — Coon & Crack II',
    shortName: 'Coon & Crack II',
    artist: 'Coon & Crack',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-04-coon-crack.webp',
    images: ['/images/products/big-04-coon-crack.webp'],
    description: 'A doua variantă din colecția Coon & Crack, cu același spirit urban și o paletă și mai dinamică de personaje.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. Imprimat eco, 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 10,
    inStock: true
  },
  {
    id: 5,
    sku: 'BIG-05',
    name: 'Big Wallet — Pulsar Synaps',
    shortName: 'Pulsar Synaps',
    artist: 'Pulsar Synaps',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-05-pulsar-synaps.webp',
    images: ['/images/products/big-05-pulsar-synaps.webp'],
    description: 'Pattern XO repetat la infinit pe fond negru cu galben electric. Geometric, graphic, inconfundabil — cu un personaj iconic alb-negru pe revers.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 20,
    inStock: true
  },
  {
    id: 6,
    sku: 'BIG-06',
    name: 'Big Wallet — Ioan I',
    shortName: 'Ioan I',
    artist: 'Ioan',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-06-ioan.webp',
    images: ['/images/products/big-06-ioan.webp'],
    description: 'Un pattern baroc-floral dens, în tonuri de maro, roșu și auriu. Bogat și elaborat — arta clasică pliată în format contemporan.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 14,
    inStock: true
  },
  {
    id: 7,
    sku: 'BIG-07',
    name: 'Big Wallet — Vanderviata I',
    shortName: 'Vanderviata I',
    artist: 'Vanderviata',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-07-vanderviata.webp',
    images: ['/images/products/big-07-vanderviata.webp'],
    description: 'Pattern alb-negru infinit de complex. Linii organice și simboluri se împletesc într-un desen hipnotic ce acoperă fiecare centimetru.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 7,
    inStock: true
  },
  {
    id: 8,
    sku: 'BIG-08',
    name: 'Big Wallet — Vanderviata II',
    shortName: 'Vanderviata II',
    artist: 'Vanderviata',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-08-vanderviata.webp',
    images: ['/images/products/big-08-vanderviata.webp', '/images/products/hero-open.webp'],
    description: 'Aceleași simboluri Vanderviata explodând în culori: roz, verde, galben, albastru, roșu. Același univers, altă energie.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 9,
    inStock: true
  },
  {
    id: 9,
    sku: 'BIG-09',
    name: 'Big Wallet — Andrei Grigorescu',
    shortName: 'Andrei Grigorescu',
    artist: 'Andrei Grigorescu',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-09-andrei-grigorescu.webp',
    images: ['/images/products/big-09-andrei-grigorescu.webp'],
    description: 'Colaje fotografice cu imagini din România — mașini de poliție, dinozauri în cartiere de bloc, cal și căruță. Ironie fină, artă serioasă.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 11,
    inStock: true
  },
  {
    id: 10,
    sku: 'BIG-10',
    name: 'Big Wallet — Bogdan Moraru',
    shortName: 'Bogdan Moraru',
    artist: 'Bogdan Moraru',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-10-bogdan-moraru.webp',
    images: ['/images/products/big-10-bogdan-moraru.webp'],
    description: 'Fotografie artistică în portocaliu și negru — mașini retro, viteze, atmosferă cinematografică années 70. Bogdan Moraru pune strada în portofelul tău.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 6,
    inStock: true
  },
  {
    id: 11,
    sku: 'BIG-11',
    name: 'Big Wallet — Ioana Moldovan I',
    shortName: 'Ioana Moldovan I',
    artist: 'Ioana Moldovan',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-11-ioana-moldovan.webp',
    images: ['/images/products/big-11-ioana-moldovan.webp'],
    description: 'Fotografie documentară intimă — o cameră cu pat roșu, o scenă de piață colorată. Un obiect de artă care poartă povești reale.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 5,
    inStock: true
  },
  {
    id: 12,
    sku: 'BIG-12',
    name: 'Big Wallet — Ioana Moldovan II',
    shortName: 'Ioana Moldovan II',
    artist: 'Ioana Moldovan',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-12-ioana-moldovan.webp',
    images: ['/images/products/big-12-ioana-moldovan.webp'],
    description: 'Fereastra unui tren, un bărbat privind afară — fotografie cu suflet, pliată în portofelul tău. Ioana Moldovan surprinde România din mers.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 4,
    inStock: true
  },
  {
    id: 13,
    sku: 'BIG-13',
    name: 'Big Wallet — Ioan II',
    shortName: 'Ioan II',
    artist: 'Ioan',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-13-ioan.webp',
    images: ['/images/products/big-13-ioan.webp'],
    description: 'Geometrie colorată și tribală — galben, roșu, verde, albastru, turcoaz în forme care se repetă și se transformă. O piesă vibrantă și caldă.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 18,
    inStock: true
  },
  {
    id: 14,
    sku: 'BIG-14',
    name: 'Big Wallet — Toybox',
    shortName: 'Toybox',
    artist: 'Toybox',
    price: 18,
    edition: 'THE BIG WALLET',
    category: 'big',
    image: '/images/products/big-14-toybox.webp',
    images: ['/images/products/big-14-toybox.webp'],
    description: 'Forme geometrice bold — triunghiuri și forme în negru, roșu și galben. Design minimalist cu impact maxim. Toybox face simplul să pară extraordinar.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Portofel mare. Greutate: 19 grame.',
    shipping: 'Livrare gratuită în România.',
    stock: 22,
    inStock: true
  },

  // ─── MINI WALLET — €8 ──────────────────────────────────────────────
  {
    id: 15,
    sku: 'MINI-01',
    name: 'Mini Wallet — Pulsar Sinaps',
    shortName: 'Pulsar Sinaps',
    artist: 'Pulsar Sinaps',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-01-pulsar-sinaps.webp',
    images: ['/images/products/mini-01-pulsar-sinaps.webp'],
    description: 'Pattern XO și personaj iconic pe mini wallet. Puțin mai mare decât cardul tău — încap 12 carduri și cash.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 30,
    inStock: true
  },
  {
    id: 16,
    sku: 'MINI-02',
    name: 'Mini Wallet — Lucia Jantos I',
    shortName: 'Lucia Jantos I',
    artist: 'Lucia Jantos',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-02-lucia-jantos.webp',
    images: ['/images/products/mini-02-lucia-jantos.webp'],
    description: 'Acuarelă sensibilă cu figură umană — tonuri delicate de albastru, roz și alb. Arta lui Lucia Jantos într-un format de buzunar.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 25,
    inStock: true
  },
  {
    id: 17,
    sku: 'MINI-03',
    name: 'Mini Wallet — Lucia Jantos II',
    shortName: 'Lucia Jantos II',
    artist: 'Lucia Jantos',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-03-lucia-jantos.webp',
    images: ['/images/products/mini-03-lucia-jantos.webp'],
    description: 'Spirale vii de culoare — roșu, verde, portocaliu, galben. O lucrare cu energie cinetică, pliată în cel mai mic portofel.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 20,
    inStock: true
  },
  {
    id: 18,
    sku: 'MINI-04',
    name: 'Mini Wallet — Lucia Jantos III',
    shortName: 'Lucia Jantos III',
    artist: 'Lucia Jantos',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-04-lucia-jantos.webp',
    images: ['/images/products/mini-04-lucia-jantos.webp'],
    description: 'Flori și forme organice în tonuri de verde, albastru, mov și galben. O grădină pliată în portofelul tău.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 18,
    inStock: true
  },
  {
    id: 19,
    sku: 'MINI-05',
    name: 'Mini Wallet — Toybox',
    shortName: 'Toybox',
    artist: 'Toybox',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-05-toybox.webp',
    images: ['/images/products/mini-05-toybox.webp'],
    description: 'Geometrie playful — triunghiuri în turcoaz, roz și galben pe fond negru. Forme simple cu impact maxim în format mini.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 33,
    inStock: true
  },
  {
    id: 20,
    sku: 'MINI-06',
    name: 'Mini Wallet — Vanderviata',
    shortName: 'Vanderviata',
    artist: 'Vanderviata',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-06-vanderviata.webp',
    images: ['/images/products/mini-06-vanderviata.webp'],
    description: 'Pattern hipnotic Vanderviata în format mini — jumătate alb-negru dens, jumătate explozie de culori. Același univers, concentrat.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 16,
    inStock: true
  },
  {
    id: 21,
    sku: 'MINI-07',
    name: 'Mini Wallet — Andrei Grigorescu I',
    shortName: 'Andrei Grigorescu I',
    artist: 'Andrei Grigorescu',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-07-andrei-grigorescu.webp',
    images: ['/images/products/mini-07-andrei-grigorescu.webp'],
    description: 'Dinozaur în cartier de bloc — scena absurdă și memorabilă a lui Grigorescu în mini format. Umor și artă în același pachet de 8€.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 12,
    inStock: true
  },
  {
    id: 22,
    sku: 'MINI-08',
    name: 'Mini Wallet — Andrei Grigorescu II',
    shortName: 'Andrei Grigorescu II',
    artist: 'Andrei Grigorescu',
    price: 8,
    edition: 'THE MINI WALLET',
    category: 'mini',
    image: '/images/products/mini-08-andrei-grigorescu.webp',
    images: ['/images/products/mini-08-andrei-grigorescu.webp'],
    description: 'Cal și căruță pe fundal suprarealist — colajele fotografice ale lui Grigorescu spun povești despre România cu umor și nostalgie.',
    materials: 'Material special eco-friendly, rezistent la apă și alcool. 100% reciclabil.',
    dimensions: 'Mini wallet — puțin mai mare decât un card bancar. Încap 12 carduri și cash.',
    shipping: 'Livrare gratuită în România.',
    stock: 10,
    inStock: true
  },

  // ─── BUNDLE — €22 ──────────────────────────────────────────────────
  {
    id: 23,
    sku: 'BUNDLE-01',
    name: 'Bundle — Big + Mini',
    shortName: 'Big + Mini Bundle',
    artist: 'Colecție',
    price: 22,
    edition: 'BUNDLE SPECIAL',
    category: 'bundle',
    image: '/images/products/bundle-hero.webp',
    images: ['/images/products/bundle-hero.webp', '/images/products/hero-lifestyle.webp'],
    description: 'Un Big Wallet și un Mini Wallet la alegere — economisești 4€ față de prețul separat. Ideal ca cadou sau dacă vrei să le ai pe amândouă.',
    materials: 'Două portofele: Big Wallet (€18) + Mini Wallet (€8). Fiecare eco-friendly, rezistent la apă și alcool.',
    dimensions: 'Big Wallet: pentru bancnote, carduri și mai mult. Mini Wallet: puțin mai mare decât un card, încap 12 carduri. Fiecare ~19g.',
    shipping: 'Livrare gratuită în România. Livrare în cutie cadou.',
    stock: 50,
    inStock: true
  }
]

export function getProductById(id) {
  return products.find(p => p.id === parseInt(id)) || null
}

export const artists = [
  'Arta Lupe', 'Coon & Crack', 'Pulsar Synaps', 'Pulsar Sinaps',
  'Ioan', 'Vanderviata', 'Andrei Grigorescu', 'Bogdan Moraru',
  'Ioana Moldovan', 'Toybox', 'Lucia Jantos'
]
